### ISSUE TITLE
Resubscribing with different tags via HTML form puts the subscriber in an unconfirmed state

### ISSUE THREAD

**Issue by benborgers** [buttondown-email/roadmap#2031]
Expected behavior would probably be either: 

1. Just change the tags, and leave them as  a subscriber. 
2. Don’t change tags unless they've unsubscribed first, and this is a re-subscription.

**Comment by EllipsisObsessed** [comment]
Adding some more details since this is relevant to the newsletter I'm working on.

Option 1 ideally there would be some form of "confirm tag changes" flow because otherwise a third party could accidentally or maliciously change a different subscriber's tags without their knowledge or consent.

Option 2, while introducing an extra step for users who want to change tags, would allow the normal confirm subscription flow to be used to prevent nonsense.

**Comment by jmduke** [comment]
@EllipsisObsessed Sorry for the delay on this one; I'll get to it early this week.
