### ISSUE TITLE
Slow export

### ISSUE THREAD

**Issue by ifpingram** [buttondown-email/roadmap#428]
The last couple of exports have taken a couple of days to process:

https://buttondown.email/settings

The last one started on:

01/12/2022 @ 11:28:45

And finished (according to email notification) on

01/14/2022 @ 05:05

They were taking a few minutes previously.

Our use case is that we run an export prior to sending the News email, so that we can find the subscribers, to unsubscribe them from our old subscriber list in a different system, that we are using to funnel subscriptions to the Buttondown system. Therefore we do not wish to send these subscribers both the email from Buttondown, as well as a notification email with link to the Buttondown article to encourage subscription, as they are already subscribed.

**Comment by jmduke** [comment]
Yup, exports are slow right now particularly because of issues with the email events system. Your use case totally makes sense; I'm trying to speed this up right this second! As a temporary measure, am I right in understanding you just need the subscribers and would be unblocked if I temporarily hide the events from your export?

**Comment by ifpingram** [comment]
Thank you; yes exactly, we need no events, just subscribers. Perhaps, a separate Subscriber export would be easiest?

**Comment by jmduke** [comment]
I actually just pushed a fix to speed this up pretty significantly; do you mind letting me know if the issue has gotten better?

**Comment by ifpingram** [comment]
Fantastic fix. Now takes about 20 seconds to run the export! Thanks!
